### ISSUE TITLE
Printing PDFs

### ISSUE THREAD

**Issue by bluemellophone** [bluemellophone/gzc-server#6]
The algorithms need to use pre-rendered map assets or Google Earth with:

wkhtmltopdf

which will render the HTML page into a nice PDF file for printing.  The web handler needs to send these files to the printer, which we need to figure out how to do nicely in Python.

**Comment by zmjjmz** [comment]
If it comes to it, there's nothing wrong with just setting up the printer beforehand and piping it through pdf2ps and lpr -- but I'll look into a way to do it from Python.

EDIT: After some cursory searching, it looks like the best way to do it is to use an lpr subprocess. This will only work on Linux/Mac however, we'd have to figure out something else for Windows.
